name: two_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7+1
  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  dartz: ^0.10.1
  http: ^1.3.0
  flutter_bloc: ^9.0.0
  internet_connection_checker: ^3.0.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.2
  bloc: ^9.0.0
  file_picker: ^9.0.0
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  data_table_2: ^2.5.18
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  lottie: ^3.3.1
  oauth2_client: ^4.1.0
  intl: ^0.20.2
  fl_chart: ^0.71.0
  signature: ^6.0.0
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  syncfusion_flutter_calendar: ^30.1.42
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: Almarai
      fonts:
        - asset: assets/fonts/almarai/Almarai-Light.ttf
          weight: 200
        - asset: assets/fonts/almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/almarai/Almarai-ExtraBold.ttf
          weight: 800
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/auth/
    - assets/icons/role/
    - assets/icons/dashboard/
    - assets/images/png/
    - assets/images/svg/
    - assets/animation/
